Packaging: single application fatJar
Signed-off-by: Alexander Bezzubov <bzz@apache.org>

diff --git a/hash b/hash
--- a/hash
+++ b/hash
@@ -1,14 +1,14 @@
 #!/bin/bash
-# Convenience script to run hashing over a set repositories in .siva files
+# Convenience script to run hashing over a set repositories
 
 E_NO_SPARK=2
 E_BUILD_FAILED=1
 
-version=$(grep "version :=" build.sbt | cut -d'=' -f 2 | tr -d ' ' | tr -d '"')
+#version=$(grep "version :=" build.sbt | cut -d'=' -f 2 | tr -d ' ' | tr -d '"')
 jar="target/gemini-uber.jar"
 build_command="./sbt assembly"
-deps_jar="target/gemini-assembly-${version}-deps.jar"
-build_deps_command="./sbt assemblyPackageDependency"
+#deps_jar="target/gemini-assembly-${version}-deps.jar"
+#build_deps_command="./sbt assemblyPackageDependency"
 current_dir="$(dirname "$0")"
 
 app_class="tech.sourced.gemini.cmd.HashSparkApp"
@@ -16,15 +16,18 @@ app_name="Gemini - hashing"
 
 hash java >/dev/null 2>&1 || { echo "Please install Java" >&2; exit 1; }
 
-if [[ ! -f "${deps_jar}" ]]; then
-    echo "${deps_jar} not found. Running build '${build_deps_command}'"
-    if ! $build_deps_command ; then
+#if [[ ! -f "${deps_jar}" ]]; then
+#    echo "${deps_jar} not found. Running build '${build_deps_command}'"
+#    if ! $build_deps_command ; then
+#        exit "${E_BUILD_FAILED}"
+#    fi
+#fi
+
+if [[ ! -f "${jar}" ]]; then
+    echo "${jar} not found. Running build '${build_command}'"
+    if ! $build_command ; then
         exit "${E_BUILD_FAILED}"
     fi
-fi
-
-if ! $build_command ; then
-    exit "${E_BUILD_FAILED}"
 fi
 
 sparkSubmit() {
@@ -47,10 +50,11 @@ sparkSubmit() {
 # https://issues.apache.org/jira/browse/SPARK-16784
 # spark.executor.extraJavaOptions=-Dlog4j.configuration=log4j-spark.properties
 
-source "$current_dir/scripts/common_params.sh"
+source "${current_dir}/scripts/common_params.sh"
+#  --jars "${deps_jar}" \
+#
 
 sparkSubmit \
-  --jars "${deps_jar}" \
   --class "${app_class}" \
   --master "${MASTER:=local[*]}" \
   --name "${app_name}" \
@@ -58,5 +62,5 @@ sparkSubmit \
   --conf "spark.default.parallelism=8" \
   --driver-java-options "-Dlog4j.configuration=jar:file:${jar}!/log4j.properties" \
   "${jar}" \
-  "${COMMAND_PARAMS[@]}"
+  "$@"
 
